[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --no-input", "python manage.py migrate"]

[start]
cmd = "gunicorn coderr_project.wsgi:application --bind 0.0.0.0:$PORT"

[variables]
PYTHON_VERSION = "3.11"