# Generated by Django 5.1.3 on 2024-11-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerdetails',
            options={'ordering': ['offer'], 'verbose_name_plural': 'Offer Details'},
        ),
    ]
