# Generated by Django 5.1.3 on 2024-11-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0002_alter_offerdetails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offers',
            options={'ordering': ['title'], 'verbose_name_plural': 'Offers'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username'], 'verbose_name_plural': 'User Profiles'},
        ),
    ]
