# Generated by Django 5.1.3 on 2024-11-18 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0005_alter_userprofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetails',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='coderr_app.offers'),
        ),
    ]
