# Generated by Django 5.1.3 on 2024-11-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0007_offerdetails_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetails',
            name='title',
            field=models.CharField(default='Offer Details', max_length=200),
        ),
    ]
