# Generated by Django 5.1.3 on 2024-11-23 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0009_order_offer_order_offer_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='coderr_app.offers'),
        ),
        migrations.AlterField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='coderr_app.offerdetails'),
        ),
    ]
